# Generated by Django 3.0.8 on 2020-09-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200907_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseleacture',
            name='lacture_type',
            field=models.CharField(choices=[('SAMPLE', 'Sample'), ('PAID', 'Paid')], default='PAID', max_length=20),
        ),
    ]
