# Generated by Django 3.0.8 on 2020-09-15 04:56

import crm.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('career_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Invalid Phone', regex='^(\\+\\d{1,3})?,?\\s?\\d{8,13}')])),
                ('dob', models.DateTimeField(auto_now=True)),
                ('experience_in_years', models.IntegerField(default=0)),
                ('discribe_yourself', models.TextField()),
                ('resume', models.FileField(upload_to='documents/crm/', validators=[crm.validators.validate_file_extension])),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Invalid Phone', regex='^(\\+\\d{1,3})?,?\\s?\\d{8,13}')])),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
