# Generated by Django 3.0.8 on 2020-09-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='discribe_yourself',
        ),
        migrations.AddField(
            model_name='career',
            name='experience_in_month',
            field=models.IntegerField(default=0),
        ),
    ]
